CREATE DATABASE QUANLYDUAN
ON PRIMARY
(
	NAME = QUANLYDUAN,
	FILENAME = 'D:\DMNhat\QUANLYDUAN.MDF',
	SIZE = 50,
	MAXSIZE = 100,
	FILEGROWTH = 5
),
(
	NAME = QUANLYDUAN_1,
	FILENAME = 'D:\DMNhat\QUANLYDUAN_1.NDF',
	SIZE = 50,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10%
)

LOG ON
(
	NAME = QUANLYDUAN_LOG,
	FILENAME = 'D:\DMNhat\QUANLYDUAN_LOG.LDF',
	SIZE = 40,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10%	
)