--1
SELECT *
FROM NHANVIEN
--2
SELECT *
FROM DEAN
--3
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE PHG=4 AND PHAI = N'NỮ'
--4
SELECT HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE MANV='009'
--5
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE DCHI LIKE N'%TP HCM'
ORDER BY NGSINH ASC
--6
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE TENNV LIKE N'%N'
ORDER BY MANV DESC
--7
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE TENNV LIKE N'_[A-D]%'
--8
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE TENNV LIKE N'_[^A-D]%'
--9
SELECT MANV, HONV, TENLOT, TENNV, NGSINH
FROM NHANVIEN
WHERE MONTH(NGSINH) >= 1 AND MONTH(NGSINH) <= 4

SELECT MANV, HONV, TENLOT, TENNV, NGSINH
FROM NHANVIEN
WHERE MONTH(NGSINH) BETWEEN 1 AND 3
--10
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE LUONG BETWEEN 30000 AND 40000
ORDER BY HONV, TENLOT, TENNV DESC
--11
SELECT HONV, TENLOT, TENNV, TENPHG
FROM NHANVIEN INNER JOIN PHONGBAN
ON MANV = TRPHG
ORDER BY NG_NHANCHUC DESC
--12
SELECT HONV, TENLOT, TENNV, TENPHG
FROM NHANVIEN LEFT JOIN PHONGBAN
ON MANV = TRPHG
ORDER BY NG_NHANCHUC DESC
--13
SELECT HONV, TENLOT, TENNV, TENTN, TN.NGSINH
FROM NHANVIEN AS NV INNER JOIN THANNHAN AS TN
ON MANV = MA_NVIEN
ORDER BY TN.NGSINH DESC
--14
SELECT HONV, TENLOT, TENNV, TENTN, TN.NGSINH
FROM NHANVIEN AS NV LEFT JOIN THANNHAN AS TN
ON MANV = MA_NVIEN
ORDER BY TN.NGSINH DESC
--15
SELECT HONV, TENLOT, TENNV, MAX(LUONG)
FROM NHANVIEN
--16
SELECT *
FROM NHANVIEN
WHERE LUONG = (
			SELECT HONV, TENLOT, TENNV, MAX(LUONG)
			FROM NHANVIEN
			)

SELECT *
FROM NHANVIEN
WHERE LUONG >= ALL (
			SELECT LUONG
			FROM NHANVIEN
			)
--17
SELECT DISTINCT LUONG
FROM NHANVIEN
WHERE LUONG <= ALL (
			SELECT LUONG
			FROM NHANVIEN
			)
--18
SELECT *
FROM NHANVIEN
WHERE LUONG <= ALL (
			SELECT LUONG
			FROM NHANVIEN
			)
--19
SELECT AVG(LUONG) AS 'LUONG TB'
FROM NHANVIEN
--20
SELECT *
FROM NHANVIEN
WHERE LUONG < (
			SELECT AVG(LUONG)
			FROM NHANVIEN
			)
--21
SELECT TOP 3 MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
ORDER BY LUONG DESC
--22
SELECT TOP 3 MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
ORDER BY LUONG ASC
--23
SELECT NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, SUM(THOIGIAN) AS 'TONG THOI GIAN LV'
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV=PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
ORDER BY SUM(THOIGIAN) DESC
--24
SELECT NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, SUM(THOIGIAN) AS 'TONG THOI GIAN LV'
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV=PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
HAVING SUM(THOIGIAN) > 35
ORDER BY SUM(THOIGIAN) DESC
--25
SELECT TOP 3 NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, SUM(THOIGIAN) AS 'TONG THOI GIAN LV'
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV=PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
ORDER BY SUM(THOIGIAN) DESC
--26
SELECT TOP 3 NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, SUM(THOIGIAN) AS 'TONG THOI GIAN LV'
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV=PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
ORDER BY SUM(THOIGIAN) ASC
--27
SELECT NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, SUM(THOIGIAN) AS 'TONG THOI GIAN LV'
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV=PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
HAVING SUM(THOIGIAN) >= ALL (
							SELECT SUM(THOIGIAN)
							FROM NHANVIEN AS NV, PHANCONG AS PC
							WHERE NV.MANV=PC.MA_NVIEN
							GROUP BY NV.MANV
							)
--28
SELECT DA.MADA, DA.TENDA, COUNT(MANV) AS 'SO LUONG NV'
FROM DEAN AS DA, NHANVIEN AS NV
WHERE DA.PHONG = NV.PHG
GROUP BY DA.MADA, DA.TENDA
--29
SELECT DA.MADA, DA.TENDA, COUNT(MANV) AS 'SO LUONG NV'
FROM DEAN AS DA, NHANVIEN AS NV
WHERE DA.PHONG = NV.PHG
GROUP BY DA.MADA, DA.TENDA
HAVING COUNT(MANV) > 2
--30
SELECT TOP 3 DA.MADA, DA.TENDA, COUNT(MANV) AS 'SO LUONG NV'
FROM DEAN AS DA, NHANVIEN AS NV
WHERE DA.PHONG = NV.PHG
GROUP BY DA.MADA, DA.TENDA
ORDER BY COUNT(MANV) DESC
--31
SELECT TOP 1 DA.MADA, DA.TENDA, COUNT(MANV) AS 'SO LUONG NV'
FROM DEAN AS DA, NHANVIEN AS NV
WHERE DA.PHONG = NV.PHG
GROUP BY DA.MADA, DA.TENDA
ORDER BY COUNT(MANV) DESC
--32
SELECT DISTINCT NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
FROM NHANVIEN AS NV, PHANCONG AS PC
WHERE NV.MANV=PC.MA_NVIEN
--33
SELECT DISTINCT NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
FROM NHANVIEN AS NV
WHERE NV.MANV NOT IN (
					SELECT MA_NVIEN
					FROM PHANCONG
					)
--34
SELECT DISTINCT MAPHG, TENPHG
FROM PHONGBAN AS PB, DEAN AS DA
WHERE PB.MAPHG = DA.PHONG
--35
SELECT DISTINCT MAPHG, TENPHG
FROM PHONGBAN AS PB
WHERE PB.MAPHG NOT IN (
					SELECT DA.PHONG
					FROM DEAN AS DA
					)