CREATE DATABASE QUANLYBANHANG
ON PRIMARY(
	NAME = QUANLYBANHANG,
	FILENAME = 'E:\0306231316\NAM 2\HQT CSDL\TUẦN 2\QUANLYBANHANG.MDF',
	SIZE = 50,
	MAXSIZE = 100,
	FILEGROWTH = 10%
)
LOG ON(
	NAME = QUANLYBANHANG_LOG,
	FILENAME = 'E:\0306231316\NAM 2\HQT CSDL\TUẦN 2\QUANLYBANHANG_LOG.LDF',
	SIZE = 50,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10
)

CREATE TABLE KHACHHANG(
	MAKH NVARCHAR(5) NOT NULL,
	TENKH NVARCHAR(30),
	DIACHI NVARCHAR(50),
	DT NVARCHAR(15),
	EMAIL NVARCHAR(30),
	CONSTRAINT PR_KHACHHANG PRIMARY KEY (MAKH)
)

CREATE TABLE VATTU(
	MAVT NVARCHAR(5) NOT NULL,
	TENVT NVARCHAR(30),
	DVT NVARCHAR(20),
	GIAMUA NUMERIC(20),
	SLTON NUMERIC(20),
	CONSTRAINT PR_VATTU  PRIMARY KEY (MAVT)
)

CREATE TABLE HOADON(
	MAHD NVARCHAR(10) NOT NULL,
	NGAY DATE,
	MAKH NVARCHAR(5),
	TONGTG NUMERIC(20),
	CONSTRAINT PR_HOADON PRIMARY KEY (MAHD)
)

CREATE TABLE CHITIETHOADON(
	MAHD NVARCHAR(10) NOT NULL,
	MAVT NVARCHAR(5) NOT NULL,
	SL NUMERIC(20),
	KHUYENMAI NUMERIC(20),
	GIABAN NUMERIC(20),
	CONSTRAINT PR_CHITIETHOADON PRIMARY KEY (MAHD, MAVT)
)

