CREATE DATABASE QUANLYDUAN
ON PRIMARY(
	NAME = QUANLYDUAN,
	FILENAME = 'E:\0306231316\NAM 2\HQT CSDL\TUẦN 2\QUANLYDUAN.MDF',
	SIZE = 50,
	MAXSIZE = 100,
	FILEGROWTH = 10%
),
(
	NAME = QUANLYDUAN_1,
	FILENAME = 'E:\0306231316\NAM 2\HQT CSDL\TUẦN 2\QUANLYDUAN_1.LDF',
	SIZE = 40,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10
)
LOG ON(
	NAME = QUANLYDUAN_LOG,
	FILENAME = 'E:\0306231316\NAM 2\HQT CSDL\TUẦN 2\QUANLYDUAN_LOG.LDF',
	SIZE = 50,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10
)

CREATE TABLE NHANVIEN(
	MANV CHAR(3) NOT NULL,
	HONV NVARCHAR(25),
	TENLOT NVARCHAR(25),
	TENNV NVARCHAR(25),
	NGSINH DATETIME,
	DCHI NVARCHAR(100),
	PHAI NVARCHAR(3),
	LUONG MONEY,
	MA_NQL CHAR(3),
	PHG INT,
	CONSTRAINT PR_NHANVIEN PRIMARY KEY (MANV)
)

CREATE TABLE PHONGBAN(
	MAPHG INT NOT NULL,
	TENPHG NVARCHAR(30),
	TRPHG CHAR(3),
	NG_NHANCHUC DATETIME,
	CONSTRAINT PR_PHONGBAN PRIMARY KEY (MAPHG)
)

CREATE TABLE THANNHAN(
	MA_NVIEN CHAR(3) NOT NULL,
	TENTN NVARCHAR(20) NOT NULL,
	PHAI NVARCHAR(3),
	NGSINH DATETIME,
	QUANHE NVARCHAR(30),
	CONSTRAINT PR_THANNHAN PRIMARY KEY (MA_NVIEN, TENTN)
)

CREATE TABLE DEAN(
	MADA INT NOT NULL,
	TENDA NVARCHAR(20),
	DDIEM_DA NVARCHAR(20),
	PHONG INT,
	CONSTRAINT PR_DEAN PRIMARY KEY (MADA)
)

CREATE TABLE DIADIEM_PHG(
	MAPHG INT NOT NULL,
	DIADIEM NVARCHAR(20),
	CONSTRAINT PR_DIADIEM_PHG PRIMARY KEY (MAPHG, DIADIEM)
)

CREATE TABLE CONGVIEC(
	MADA INT NOT NULL,
	STT INT NOT NULL,
	TEN_CONG_VIEC NVARCHAR(50),
	CONSTRAINT PR_CONGVIEC PRIMARY KEY (MADA, STT)
)

CREATE TABLE PHANCONG(
	MA_NVIEN CHAR(3) NOT NULL,
	MADA INT NOT NULL,
	STT INT NOT NULL,
	THOIGIAN INT,
	CONSTRAINT PR_PHANCONG PRIMARY KEY (MA_NVIEN, MADA, STT)
)


--1
ALTER TABLE NHANVIEN
ADD NGAYVAOLAM DATETIME DEFAULT GETDATE()
--2
ALTER TABLE THANNHAN
ADD HOTN NVARCHAR(25)
--3
ALTER TABLE NHANVIEN
ALTER COLUMN TENNV NVARCHAR(50)
--4
ALTER TABLE THANNHAN
ALTER COLUMN HOTN NVARCHAR(50)
--5
EXEC SP_RENAME 'NHANVIEN.MANV','MANHANVIEN','COLUMN'
--6
EXEC SP_RENAME 'THANNHAN.HOTN','HOTHANNHAN','COLUMN'
--7
EXEC SP_RENAME 'NHANVIEN','NV'
--8
EXEC SP_RENAME 'DIADIEM_PHG','DIADIEMPHONG'
--9
ALTER TABLE NV
DROP COLUMN DCHI
--10
ALTER TABLE NV
DROP COLUMN MANHANVIEN
--11
DROP TABLE PHANCONG
--12
DROP TABLE NV
