--1
SELECT *
FROM NHANVIEN
ORDER BY NGSINH ASC
--2
SELECT *
FROM NHANVIEN
ORDER BY YEAR(GETDATE()) - YEAR(NGSINH) ASC
--3
SELECT *
FROM NHANVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= 60 AND PHAI LIKE N'NAM' OR YEAR(GETDATE()) - YEAR(NGSINH) >= 55 AND PHAI LIKE N'NỮ'
--4
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV, NGSINH
FROM NHANVIEN
WHERE MONTH(GETDATE()) = MONTH(NGSINH)
--5
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG AND TENPHG LIKE 'NGHIÊN CỨU'
ORDER BY MANV DESC
--6 
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN, PHANCONG
WHERE MANV =  MA_NVIEN AND MADA = 10
ORDER BY MANV ASC
--7
SELECT TOP 2 HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN
WHERE PHG = (
	SELECT MAPHG
	FROM PHONGBAN, DEAN
	WHERE PHONG = MAPHG AND TENPHG LIKE 'NGHIÊN CỨU' AND TENDA LIKE N'TIN HỌC HÓA'
)
--8
SELECT TOP 3 HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN
ORDER BY LUONG DESC
--9
SELECT TOP 2 HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG AND TENPHG LIKE N'NGHIÊN CỨU'
ORDER BY LUONG ASC
--10
SELECT MAX(LUONG) AS 'LƯƠNG CAO NHẤT', AVG(LUONG) AS 'LƯƠNG TRUNG BÌNH', MIN(LUONG) AS 'LƯƠNG THẤP NHẤT'
FROM NHANVIEN
--11
SELECT COUNT(MANV) AS 'SỐ NHÂN VIÊN'
FROM NHANVIEN
--12
SELECT COUNT(MANV) AS 'SỐ NHÂN VIÊN PHÒNG ĐIỀU HÀNH'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG AND TENPHG LIKE N'ĐIỀU HÀNH' 
--13
SELECT COUNT(MANV) AS 'SỐ NHÂN VIÊN THAM GIA TIN HỌC HÓA'
FROM NHANVIEN AS NV, PHANCONG AS PC, DEAN AS DA
WHERE PC.MA_NVIEN = NV.MANV AND PC.MADA = DA.MADA AND DA.TENDA = N'Tin học hoá'
--14
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN
WHERE LUONG >= ALL (
	SELECT LUONG
	FROM NHANVIEN
)
--15
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN
WHERE LUONG <= ALL (
	SELECT LUONG
	FROM NHANVIEN
)
--16
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTEN, MANV, LUONG
FROM NHANVIEN 
WHERE LUONG = (
	SELECT MAX(LUONG)
	FROM NHANVIEN, PHONGBAN
	WHERE PHG = MAPHG AND TENPHG LIKE N'NGHIÊN CỨU'
)
--17
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN
WHERE LUONG >= (
	SELECT AVG(LUONG)
	FROM NHANVIEN
)
--18
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS HOTENNV, MANV
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG AND TENPHG LIKE N'ĐIỀU HÀNH' AND LUONG >= (
	SELECT AVG(LUONG)
	FROM NHANVIEN, PHONGBAN
	WHERE PHG = MAPHG AND TENPHG LIKE N'ĐIỀU HÀNH'
)
--19
SELECT MAPHG, TENPHG , AVG(LUONG)
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
--20
SELECT MAPHG, TENPHG , SUM(LUONG) AS 'TỔNG LƯƠNG', AVG(LUONG) AS 'LƯƠNG TRUNG BÌNH'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
--21
SELECT MAPHG, TENPHG , MIN(LUONG) AS 'LƯƠNG NHỎ NHẤT', AVG(LUONG) AS 'LƯƠNG TRUNG BÌNH'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
--22
SELECT MAPHG, TENPHG , COUNT(MANV) AS 'SỐ NHÂN VIÊN' 
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
--23
SELECT MAPHG, TENPHG , SUM(LUONG) AS 'TỔNG LƯƠNG', AVG(LUONG) AS 'LƯƠNG TRUNG BÌNH', COUNT(MANV) AS 'SỐ NHÂN VIÊN'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
--24
SELECT MAPHG, TENPHG, AVG(LUONG) AS 'LƯƠNG TRUNG BÌNH'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
HAVING AVG(LUONG) > 40000
--25
SELECT MAPHG, TENPHG, COUNT(MANV) AS 'SỐ NHÂN VIÊN' 
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
HAVING COUNT(MANV) > 2
--26
SELECT MAPHG, TENPHG , SUM(LUONG) AS 'TỔNG LƯƠNG'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
HAVING SUM(LUONG) > 50000
--27
SELECT MAPHG, TENPHG, AVG(LUONG) AS 'LƯƠNG TRUNG BÌNH'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
HAVING AVG(LUONG) >= ALL(
	SELECT AVG(LUONG)
	FROM NHANVIEN, PHONGBAN
	WHERE PHG = MAPHG
	GROUP BY MAPHG, TENPHG
)
--28
SELECT TOP 2 MAPHG, TENPHG, SUM(LUONG) AS 'TỔNG LƯƠNG'
FROM NHANVIEN, PHONGBAN
WHERE PHG = MAPHG
GROUP BY MAPHG, TENPHG
ORDER BY SUM(LUONG) DESC
--29
SELECT SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM'
FROM NHANVIEN, PHANCONG
WHERE MANV = MA_NVIEN
--30
SELECT MANV, TENNV, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM'
FROM NHANVIEN, PHANCONG
WHERE MANV = MA_NVIEN
GROUP BY MANV, TENNV
--31
SELECT MANV, TENNV, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM'
FROM NHANVIEN, PHANCONG
WHERE MANV = MA_NVIEN
GROUP BY MANV, TENNV
HAVING SUM(THOIGIAN) >= 50
--32
SELECT DA.MADA, TENDA, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM ĐỀ ÁN'
FROM DEAN AS DA, PHANCONG AS PC
WHERE  PC.MADA = DA.MADA
GROUP BY DA.MADA, TENDA
--33
SELECT DA.MADA, TENDA, COUNT(MA_NVIEN) AS 'SỐ LƯỢNG NHÂN VIÊN'
FROM DEAN AS DA, PHANCONG AS PC
WHERE  PC.MADA = DA.MADA
GROUP BY DA.MADA, TENDA
--34
SELECT DA.MADA, TENDA, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM ĐỀ ÁN'
FROM DEAN AS DA, PHANCONG AS PC
WHERE  PC.MADA = DA.MADA
GROUP BY DA.MADA, TENDA
HAVING SUM(THOIGIAN)  <= 60
--35
SELECT MANV, TENNV, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM'
FROM NHANVIEN, PHANCONG
WHERE MANV = MA_NVIEN
GROUP BY MANV, TENNV
HAVING SUM(THOIGIAN) >= ALL(
	SELECT SUM(THOIGIAN)
	FROM NHANVIEN, PHANCONG
	WHERE MANV = MA_NVIEN
	GROUP BY MANV, TENNV
)
--36
SELECT MANV, TENNV, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM'
FROM NHANVIEN, PHANCONG
WHERE MANV = MA_NVIEN
GROUP BY MANV, TENNV
HAVING SUM(THOIGIAN) <= ALL(
	SELECT SUM(THOIGIAN)
	FROM NHANVIEN, PHANCONG
	WHERE MANV = MA_NVIEN
	GROUP BY MANV, TENNV
)
--37
SELECT DA.MADA, TENDA, SUM(THOIGIAN) AS 'TỔNG GIỜ LÀM ĐỀ ÁN'
FROM DEAN AS DA, PHANCONG AS PC
WHERE  PC.MADA = DA.MADA
GROUP BY DA.MADA, TENDA
HAVING SUM(THOIGIAN) >= ALL(
	SELECT SUM(THOIGIAN)
	FROM DEAN AS DA, PHANCONG AS PC
	WHERE  PC.MADA = DA.MADA
	GROUP BY DA.MADA, TENDA
)





