CREATE DATABASE QUANLYHOCVIEN
GO
USE QUANLYHOCVIEN
GO
--1. Tạo quan hệ và khai báo tất cả các ràng buộc khóa chính, khóa ngoại. Thêm vào 3 thuộc tính
--GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.
CREATE TABLE HOCVIEN(
	MAHV CHAR(9),
	HO NVARCHAR(25),
	TEN NVARCHAR(25),
	NGSINH DATE,
	GIOITINH NVARCHAR(5),
	NOISINH NVARCHAR(25),
	MALOP CHAR(9)
)
CREATE TABLE LOP (
	MALOP CHAR(9),
	TENLOP NVARCHAR(25),
	TRGLOP CHAR(9),
	SISO NUMERIC(3), 
	MAGVCN CHAR(9)
)
CREATE TABLE KHOA (
	MAKHOA CHAR(9),
	TENKHOA NVARCHAR(25),
	NGTLAP DATE,
	TRGKHOA CHAR(9)
)
CREATE TABLE MONHOC (
	ΜΑΜΗ CHAR(9),
	ΤΕΝMH NVARCHAR(25),
	TCLT NUMERIC(3),
	TCТН NUMERIC(3),
	МАКНОА CHAR(9)
)
CREATE TABLE DIEUKIEN (
	ΜΑΜΗ CHAR(9),
	ΜΑMH_TRUOC CHAR(9)
)
CREATE TABLE GIAOVIEN (
	MAGV CHAR(9),
	HOTEN NVARCHAR(25),
	HOCVI NVARCHAR(25),
	HOCHAM NVARCHAR(25),
	GIOITINH VARCHAR(5),
	NGSINH DATE,
	NGVL DATE,
	HESO VARCHAR(5),
	MUCLUONG MONEY,
	MAKHOA CHAR(9)
)
CREATE TABLE GIANGDAY (
	MALOP CHAR(9),
	MAMH CHAR(9),
	MAGV CHAR(9),
	HOCKY NVARCHAR(25),
	NAM VARCHAR(5),
	TUNGAY DATE,
	DENNGAY DATE
)
CREATE TABLE KETQUATHI (
	MAHV CHAR(9),
	MAMH CHAR(9),
	LANTHI VARCHAR(5),
	NGTHI DATE,
	DIEM NUMERIC(2),
	KQUA NVARCHAR(25)
)

--KHÓA CHÍNH HỌC VIÊN
ALTER TABLE HOCVIEN
ALTER COLUMN MAHV CHAR(9) NOT NULL

ALTER TABLE HOCVIEN
ADD CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV)
--KHÓA CHÍNH LỚP
ALTER TABLE LOP
ALTER COLUMN MALOP CHAR(9) NOT NULL

ALTER TABLE LOP
ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
--KHÓA CHÍNH KHOA
ALTER TABLE KHOA
ALTER COLUMN MAKHOA CHAR(9) NOT NULL

ALTER TABLE KHOA
ADD CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
--KHÓA CHÍNH MÔN HỌC
ALTER TABLE MONHOC
ALTER COLUMN MAMH CHAR(9) NOT NULL

ALTER TABLE MONHOC
ADD CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH)
--KHÓA CHÍNH ĐIỀU KIỆN
ALTER TABLE DIEUKIEN
ALTER COLUMN MAMH CHAR(9) NOT NULL

ALTER TABLE DIEUKIEN
ALTER COLUMN MAMH_TRUOC CHAR(9) NOT NULL

ALTER TABLE DIEUKIEN
ADD CONSTRAINT PK_DIEUKIEN PRIMARY KEY (MAMH, MAMH_TRUOC)
--KHÓA CHÍNH GIÁO VIÊN
ALTER TABLE GIAOVIEN
ALTER COLUMN MAGV CHAR(9) NOT NULL

ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
--KHÓA CHÍNH GIẢNG DẠY
ALTER TABLE GIANGDAY
ALTER COLUMN MALOP CHAR(9) NOT NULL

ALTER TABLE GIANGDAY
ALTER COLUMN MAMH CHAR(9) NOT NULL

ALTER TABLE GIANGDAY
ADD CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH)
--KHÓA CHÍNH KẾT QUẢ THI
ALTER TABLE KETQUATHI
ALTER COLUMN MAHV CHAR(9) NOT NULL

ALTER TABLE KETQUATHI
ALTER COLUMN MAMH CHAR(9) NOT NULL

ALTER TABLE KETQUATHI
ALTER COLUMN LANTHI CHAR(9) NOT NULL

ALTER TABLE KETQUATHI
ADD CONSTRAINT PK_KETQUATHI PRIMARY KEY (MAHV,MAMH, LANTHI)

--KHÓA NGOẠI HỌC VIÊN
ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
--KHÓA NGOẠI LỚP
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN (MAHV),
	CONSTRAINT FK_LOP_GVCN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN (MAGV)
--KHÓA NGOẠI KHOA
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN (MAGV)
--KHÓA NGOẠI MÔN HỌC
ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA)
--KHÓA NGOẠI ĐIỀU KIỆN
ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH),
	CONSTRAINT FK_DK_MHTRC FOREIGN KEY (MAMH_TRC) REFERENCES MONHOC (MAMH)
--KHÓA NGOẠI GIÁO VIÊN
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA)
--KHÓA NGOẠI GIẢNG DẠY
ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP),
	CONSTRAINT FK_GIANGDAY_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN (MAGV),
	CONSTRAINT FK_GIANGDAY_MH FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH)
--KHÓA NGOẠI KẾT QUẢ THI
ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN (MAHV),
	CONSTRAINT FK_KETQUATHI_MH FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH)
--THÊM THUỘC TÍNH 
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(25)

ALTER TABLE HOCVIEN
ADD DIEMTB FLOAT

ALTER TABLE HOCVIEN
ADD XEPHANG VARCHAR(20)
--2. Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.
CREATE RULE MALE_OR_FEMALE
AS @GENDER LIKE 'NAM' OR @GENDER LIKE 'NU'

EXEC SP_BINDRULE 'MALE_OR_FEMALE', 'HOCVIEN.GIOITINH'
EXEC SP_BINDRULE 'MALE_OR_FEMALE', 'GIAOVIEN.GIOITINH'
--3. Điểm số của một lần thi có giá trị từ 0 đến 10
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KETQUATHI
CHECK (DIEM >= 0 AND DIEM <= 10)
--4. Kết quả thi là “Dat” nếu điểm từ 5 đến 10 và “Khong dat” nếu điểm nhỏ hơn 5.
ALTER TABLE KETQUATHI
ADD CONSTRAINT _CK_KETQUATHI
CHECK ((KETQUA = 'DAT' AND DIEM BETWEEN 5 AND 10) OR DIEM < 5 AND KETQUA = 'KHONG DAT')
--5. Học viên thi một môn tối đa 3 lần.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KETQUATHI_LANTHI
CHECK (LANTHI < 4)
--6. Học kỳ chỉ có giá trị từ 1 đến 3.
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY
CHECK (HOCKY BETWEEN 1 AND 3)
--7. Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”.
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GIAOVIEN_HOCVI
CHECK (HOCVI IN ('CN', 'KS', 'THS', 'TS', 'PTS'))
--8. Học viên ít nhất là 18 tuổi.
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_HOCVIEN_TUOI
CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)
--9. Giảng dạy một môn học ngày bắt đầu (TUNGAY) phải nhỏ hơn ngày kết thúc
--(DENNGAY).
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_GIANGDAY
CHECK (TUNGAY < DENNGAY)
--10. Giáo viên khi vào làm ít nhất là 22 tuổi.
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GIAOVIEN_TUOI
CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 22)
--11. Tất cả các môn học đều có số tín chỉ lý thuyết và tín chỉ thực hành chênh lệch nhau không
--quá 3
ALTER TABLE MONHOC
ADD CONSTRAINT CK_MONHOC
CHECK (TCLT - TCTH > 3 AND TCTH - TCLT > 3)