--9
CREATE PROC SP_LKNV (@TUOI INT)
AS
SELECT *
FROM NHANVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= @TUOI
ORDER BY YEAR(GETDATE()) - YEAR(NGSINH) DESC

EXEC SP_LKNV 40
--10
CREATE PROC SP_TUOIHUUNAMNU (@TUOINAM INT, @TUOINU INT)
AS
SELECT *
FROM NHANVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= @TUOINAM AND PHAI LIKE N'NAM'
OR YEAR(GETDATE()) - YEAR(NGSINH) >= @TUOINU AND PHAI LIKE N'NỮ'
ORDER BY YEAR(GETDATE()) - YEAR(NGSINH) DESC

EXEC SP_TUOIHUUNAMNU 60, 55
--11
CREATE PROC SP_TANGLUONG (@MAPHG INT)
AS
UPDATE NHANVIEN
SET LUONG = LUONG * 1.1
FROM PHONGBAN
WHERE PHG = MAPHG AND MAPHG = @MAPHG

EXEC SP_TANGLUONG 1

--12
CREATE PROC SP_TANGTG (@MADA INT, @MANV CHAR(9), @SOTT INT, @THOIGIAN INT)
AS
UPDATE PHANCONG
SET THOIGIAN = THOIGIAN + @THOIGIAN
WHERE MADA = @MADA AND @MANV = MA_NVIEN AND @SOTT = STT

EXEC SP_TANGTG 1, '009', 2, 10
--13
CREATE PROC SP_XOAPC (@MADA INT)
AS
DELETE FROM PHANCONG WHERE MADA = @MADA

EXEC SP_XOAPC 2
--14
CREATE PROC SP_XOADA (@MADA INT)
AS
DELETE FROM PHANCONG WHERE MADA = @MADA
DELETE FROM CONGVIEC WHERE MADA = @MADA
DELETE FROM DEAN WHERE MADA = @MADA

EXEC SP_XOADA 1
--15
CREATE PROC SP_THEMPC (@MADA INT, @MANV CHAR(9), @SOTT INT, @THOIGIAN INT)
AS
INSERT INTO PHANCONG (MADA, MA_NVIEN, STT, THOIGIAN) VALUES
(@MADA, @MANV, @SOTT, @THOIGIAN)

DROP PROC SP_THEMPC

EXEC SP_THEMPC 30, '009' , 1, 15
--16
CREATE PROC SP_THEMNV (@HONV nvarchar(15),
	@TENLOT nvarchar(15),
	@TENNV nvarchar(15),
	@MANV char(9),
	@NGSINH date,
	@DCHI nvarchar(30),
	@PHAI nvarchar(3),
	@LUONG float,
	@MA_NQL  char(9),
	@PHG  int)
AS
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG) VALUES
(@HONV, @TENLOT, @TENNV, @MANV, @NGSINH, @DCHI, @PHAI, @LUONG, @MA_NQL, @PHG)

EXEC SP_THEMNV N'Nguyễn', N'Thanh', N'Tùng', '100', '20/08/1962', N'222 Nguyễn Văn Cừ, Tp HCM', N'Nam', '40000', NULL, NULL

SET DATEFORMAT	dmy

--17
CREATE PROC SP_LUONGTB (@TUOI INT, @LUONGTB MONEY OUT)
AS
EXEC SP_LKNV @TUOI = @TUOI
SELECT @LUONGTB = AVG(LUONG)
FROM NHANVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= @TUOI
GO
DECLARE @LUONGTB MONEY
EXEC SP_LUONGTB 60, @LUONGTB OUT
SELECT YEAR(GETDATE()) - YEAR(NGSINH), AVG(LUONG)
FROM NHANVIEN
GROUP BY YEAR(GETDATE()) - YEAR(NGSINH)
HAVING AVG(LUONG) > @LUONGTB

--18
CREATE PROC SP_SLHUU (@TUOINAM INT, @TUOINU INT, @SLNVNU INT OUT, @SLNVNAM INT OUT)
AS
SELECT @SLNVNU = COUNT(*)
FROM NHANVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= @TUOINU AND PHAI LIKE N'NỮ'

SELECT @SLNVNAM = COUNT(*)
FROM NHANVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= @TUOINAM AND PHAI LIKE N'NAM'

EXEC SP_TUOIHUUNAMNU 60, 55